# Generated by Django 5.2.16 on 2026-10-10 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_brand_brand_kit_brand_brand_kit_updated_at_and_more"),
        ("orders", "0004_b2border_delivered_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HSNCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "uqc",
                    models.CharField(
                        choices=[
                            ("KGS", "KGS — Kilograms"),
                            ("PCS", "PCS — Pieces"),
                            ("NOS", "NOS — Numbers"),
                            ("PAC", "PAC — Packs"),
                        ],
                        default="KGS",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hsn_codes",
            },
        ),
        migrations.CreateModel(
            name="InvoiceSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fiscal_year",
                    models.CharField(help_text="e.g. '2026-27'", max_length=7),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("INV", "Tax Invoice"), ("CN", "Credit Note")],
                        max_length=3,
                    ),
                ),
                ("prefix", models.CharField(blank=True, max_length=10)),
                ("pad_width", models.PositiveSmallIntegerField(default=7)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "invoice_series",
            },
        ),
        migrations.CreateModel(
            name="LegalEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_name", models.CharField(max_length=255)),
                ("trade_name", models.CharField(blank=True, max_length=255)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("pan", models.CharField(blank=True, max_length=10)),
                (
                    "state_code",
                    models.CharField(
                        choices=[
                            ("01", "Jammu and Kashmir"),
                            ("02", "Himachal Pradesh"),
                            ("03", "Punjab"),
                            ("04", "Chandigarh"),
                            ("05", "Uttarakhand"),
                            ("06", "Haryana"),
                            ("07", "Delhi"),
                            ("08", "Rajasthan"),
                            ("09", "Uttar Pradesh"),
                            ("10", "Bihar"),
                            ("11", "Sikkim"),
                            ("12", "Arunachal Pradesh"),
                            ("13", "Nagaland"),
                            ("14", "Manipur"),
                            ("15", "Mizoram"),
                            ("16", "Tripura"),
                            ("17", "Meghalaya"),
                            ("18", "Assam"),
                            ("19", "West Bengal"),
                            ("20", "Jharkhand"),
                            ("21", "Odisha"),
                            ("22", "Chhattisgarh"),
                            ("23", "Madhya Pradesh"),
                            ("24", "Gujarat"),
                            ("26", "Dadra and Nagar Haveli and Daman and Diu"),
                            ("27", "Maharashtra"),
                            ("29", "Karnataka"),
                            ("30", "Goa"),
                            ("31", "Lakshadweep"),
                            ("32", "Kerala"),
                            ("33", "Tamil Nadu"),
                            ("34", "Puducherry"),
                            ("35", "Andaman and Nicobar Islands"),
                            ("36", "Telangana"),
                            ("37", "Andhra Pradesh"),
                            ("38", "Ladakh"),
                            ("97", "Other Territory"),
                        ],
                        default="32",
                        max_length=2,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("fssai_no", models.CharField(blank=True, max_length=50)),
                ("email", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                ("bank_account_no", models.CharField(blank=True, max_length=50)),
                ("bank_ifsc", models.CharField(blank=True, max_length=20)),
                ("bank_branch", models.CharField(blank=True, max_length=255)),
                ("upi_id", models.CharField(blank=True, max_length=100)),
                (
                    "jurisdiction",
                    models.CharField(blank=True, default="Kozhikode", max_length=100),
                ),
                ("signatory", models.CharField(blank=True, max_length=255)),
                ("b2b_terms", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "legal entities",
                "db_table": "legal_entities",
            },
        ),
        migrations.CreateModel(
            name="HSNRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total rate, e.g. 5.00",
                        max_digits=5,
                    ),
                ),
                (
                    "cess_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hsn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="billing.hsncode",
                    ),
                ),
            ],
            options={
                "db_table": "hsn_rates",
                "ordering": ["hsn_id", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=16)),
                ("fiscal_year", models.CharField(max_length=7)),
                ("invoice_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled (credit note issued, reissued)"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "supply_type",
                    models.CharField(
                        choices=[("B2B", "B2B"), ("B2C", "B2C")], max_length=3
                    ),
                ),
                ("price_mode", models.CharField(max_length=10)),
                ("seller_legal_name", models.CharField(max_length=255)),
                ("seller_trade_name", models.CharField(blank=True, max_length=255)),
                ("seller_gstin", models.CharField(max_length=15)),
                ("seller_address", models.TextField(blank=True)),
                ("seller_state_code", models.CharField(max_length=2)),
                ("seller_fssai", models.CharField(blank=True, max_length=50)),
                ("seller_phone", models.CharField(blank=True, max_length=50)),
                ("seller_email", models.CharField(blank=True, max_length=255)),
                (
                    "seller_extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Bank, jurisdiction, signatory, terms",
                    ),
                ),
                ("brand_name", models.CharField(blank=True, max_length=255)),
                ("bill_to_name", models.CharField(max_length=255)),
                ("bill_to_gstin", models.CharField(blank=True, max_length=15)),
                ("bill_to_address", models.TextField(blank=True)),
                ("bill_to_state_code", models.CharField(blank=True, max_length=2)),
                ("bill_to_pincode", models.CharField(blank=True, max_length=10)),
                ("ship_to_same", models.BooleanField(default=True)),
                ("ship_to_name", models.CharField(blank=True, max_length=255)),
                ("ship_to_address", models.TextField(blank=True)),
                ("ship_to_state_code", models.CharField(blank=True, max_length=2)),
                ("ship_to_pincode", models.CharField(blank=True, max_length=10)),
                ("ship_to_gstin", models.CharField(blank=True, max_length=15)),
                ("place_of_supply_state", models.CharField(max_length=2)),
                ("is_interstate", models.BooleanField(default=False)),
                ("customer_po_no", models.CharField(blank=True, max_length=100)),
                ("customer_po_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "gross_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "taxable_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cgst_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sgst_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "igst_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cess_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "round_off",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("irn", models.CharField(blank=True, max_length=64)),
                ("ack_no", models.CharField(blank=True, max_length=30)),
                ("ack_date", models.DateTimeField(blank=True, null=True)),
                ("signed_qr", models.TextField(blank=True)),
                ("eway_bill_no", models.CharField(blank=True, max_length=20)),
                ("eway_bill_date", models.DateField(blank=True, null=True)),
                ("pdf_file", models.FileField(blank=True, upload_to="gst/invoices/")),
                ("pdf_sha256", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "b2b_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="orders.b2border",
                    ),
                ),
                (
                    "b2c_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="orders.order",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.brand",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reissue_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reissues",
                        to="billing.invoice",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="billing.invoiceseries",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="billing.legalentity",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-invoice_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=16)),
                ("fiscal_year", models.CharField(max_length=7)),
                ("credit_note_date", models.DateField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sales_return", "Sales return"),
                            ("post_sale_discount", "Post-sale discount"),
                            ("deficiency", "Deficiency in goods"),
                            ("correction", "Correction in invoice"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "taxable_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cgst_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sgst_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "igst_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cess_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("irn", models.CharField(blank=True, max_length=64)),
                ("ack_no", models.CharField(blank=True, max_length=30)),
                ("ack_date", models.DateTimeField(blank=True, null=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, upload_to="gst/credit_notes/"),
                ),
                ("pdf_sha256", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.brand",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="billing.invoice",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="billing.invoiceseries",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="billing.legalentity",
                    ),
                ),
            ],
            options={
                "db_table": "credit_notes",
                "ordering": ["-credit_note_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("GOODS", "Goods"), ("SHIPPING", "Shipping")],
                        default="GOODS",
                        max_length=8,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("hsn_code", models.CharField(blank=True, max_length=8)),
                ("uqc", models.CharField(blank=True, max_length=3)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("source_quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gross_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "taxable_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cess_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_free", models.BooleanField(default=False)),
                (
                    "b2b_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orders.b2borderitem",
                    ),
                ),
                (
                    "b2c_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_lines",
                "ordering": ["invoice_id", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="CreditNoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                ("source_quantity", models.PositiveIntegerField()),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "taxable_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cess_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("restock", models.BooleanField(default=False)),
                (
                    "credit_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="billing.creditnote",
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_lines",
                        to="billing.invoiceline",
                    ),
                ),
            ],
            options={
                "db_table": "credit_note_lines",
                "ordering": ["credit_note_id", "line_no"],
            },
        ),
        migrations.AddField(
            model_name="invoiceseries",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="series",
                to="billing.legalentity",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceseries",
            constraint=models.UniqueConstraint(
                fields=("entity", "fiscal_year", "doc_type"),
                name="uniq_series_entity_fy_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("series", "number"), name="uniq_invoice_series_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("b2b_order__isnull", True), ("b2c_order__isnull", False)),
                    models.Q(("b2b_order__isnull", False), ("b2c_order__isnull", True)),
                    _connector="OR",
                ),
                name="invoice_exactly_one_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("b2c_order__isnull", False), ("status", "active")),
                fields=("b2c_order",),
                name="uniq_active_invoice_b2c_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("b2b_order__isnull", False), ("status", "active")),
                fields=("b2b_order",),
                name="uniq_active_invoice_b2b_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.UniqueConstraint(
                fields=("series", "number"), name="uniq_credit_note_series_number"
            ),
        ),
    ]
