# Generated by Django 5.2.16 on 2026-10-10 23:04

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_seed_gst"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditnote",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                storage=billing.models.private_document_storage,
                upload_to="gst/credit_notes/",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                storage=billing.models.private_document_storage,
                upload_to="gst/invoices/",
            ),
        ),
    ]
