# Generated by Django 5.2.16 on 2026-10-10 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("core", "0002_brand_brand_kit_brand_brand_kit_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="legal_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brands",
                to="billing.legalentity",
            ),
        ),
    ]
