# Generated by Django 5.2.16 on 2026-08-09 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        ('orders', '0002_alter_b2border_order_date_alter_order_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('b2c_order', 'B2C Order'), ('b2b_order', 'B2B Order')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('income_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('b2b_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to='orders.b2border')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='core.brand')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to='orders.order')),
            ],
            options={
                'db_table': 'incomes',
                'constraints': [models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order',), name='uniq_income_per_b2c_order'), models.UniqueConstraint(condition=models.Q(('b2b_order__isnull', False)), fields=('b2b_order',), name='uniq_income_per_b2b_order')],
            },
        ),
    ]
