"""
Django settings for Varthaai project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a local .env file (not committed).
load_dotenv(BASE_DIR / '.env')


def env(key, default=None):
    return os.environ.get(key, default)


def env_bool(key, default=False):
    return env(key, str(default)).lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Fall back to the insecure dev key when the env var is unset OR blank.
SECRET_KEY = env('DJANGO_SECRET_KEY') or 'django-insecure-we)w5rz1q4$b0vt!sgu6i6=^=-k$s8(@@tx350gwgr75!3rbwc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = [h for h in env('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h]

# Hosts trusted for unsafe (POST) requests. Django 4+ requires the scheme.
# e.g. DJANGO_CSRF_TRUSTED_ORIGINS=http://varthaai.com,http://www.varthaai.com
CSRF_TRUSTED_ORIGINS = [o for o in env('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o]


# Application definition

DJANGO_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
]

LOCAL_APPS = [
    'core',
    'accounts',
    'products',
    'orders',
    'crm',
    'finance',
    'marketing',
    'storefront',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# Custom admin/staff identity — see accounts.AdminUser.
AUTH_USER_MODEL = 'accounts.AdminUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Varthaai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.admin_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Varthaai.wsgi.application'

# Auth — admin panel uses session login backed by the custom AdminUser model.
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

# CSRF cookie must be readable by jQuery so it can send the X-CSRFToken header.
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = True


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', 'varthaai_db'),
        'USER': env('DB_USER', 'varthaai'),
        'PASSWORD': env('DB_PASSWORD', ''),
        'HOST': env('DB_HOST', '127.0.0.1'),
        'PORT': env('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Leading slashes make static/media URLs absolute so they resolve correctly on
# nested pages (/admin/…, /shop/, /blog-detail/) and in JS-injected <img src>.
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploaded media (flavor images, receipts, QR codes, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework — all admin/storefront APIs return {success, message, data}.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'core.api.api_exception_handler',
    'UNAUTHENTICATED_USER': None,
}

# Razorpay (storefront checkout) — populated via .env in Phase 7.
RAZORPAY_KEY_ID = env('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = env('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = env('RAZORPAY_WEBHOOK_SECRET', '')

# Storefront (Phase 15). All secrets live in .env — never hardcode them here.
# The storefront resolves its brand from STOREFRONT_BRAND_ID (default 1).
STOREFRONT_BRAND_ID = int(env('STOREFRONT_BRAND_ID', '1'))

# 2Factor OTP (https://2factor.in). Blank key => OTP send/verify is disabled.
TWOFACTOR_API_KEY = env('TWOFACTOR_API_KEY', '')
OTP_TEMPLATE = env('OTP_TEMPLATE', 'Varthaai Login OTP')

# Google reCAPTCHA v3. Blank secret => verification is skipped (dev convenience).
RECAPTCHA_SITE_KEY = env('RECAPTCHA_SITE_KEY', '')
RECAPTCHA_SECRET = env('RECAPTCHA_SECRET', '')

# Telegram new-order notifications. Blank token => notifications are skipped.
TELEGRAM_BOT_TOKEN = env('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_GROUP_CHAT_ID = env('TELEGRAM_GROUP_CHAT_ID', '')

WHATSAPP_BUSINESS_NUMBER = env('WHATSAPP_BUSINESS_NUMBER', '919400557445')

# Loyalty points (ported from PHP config.php constants).
PURCHASE_POINTS_PERCENTAGE = int(env('PURCHASE_POINTS_PERCENTAGE', '10'))
REVIEW_POINTS = int(env('REVIEW_POINTS', '5'))
FEEDBACK_POINTS = int(env('FEEDBACK_POINTS', '5'))
REFERRAL_POINTS = int(env('REFERRAL_POINTS', '50'))
