# Generated by Django 5.2.16 on 2026-07-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='reference',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='pointstransaction',
            constraint=models.UniqueConstraint(fields=('user', 'reference'), name='uniq_points_user_reference'),
        ),
    ]
