# Generated by Django 5.2.16 on 2026-10-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_pointstransaction_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('staff', 'Staff'), ('employee', 'Employee')], default='staff', max_length=20),
        ),
    ]
