# Generated by Django 5.2.16 on 2026-10-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_adminuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
