# Generated by Django 5.2.16 on 2026-07-31 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('query', 'Query')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('analyzing', 'Analyzing'), ('awaiting_input', 'Awaiting input'), ('ready', 'Ready'), ('pr_requested', 'PR requested'), ('pr_open', 'PR open'), ('changes_requested', 'Changes requested'), ('revising', 'Revising'), ('pr_updated', 'PR updated'), ('closed', 'Closed'), ('failed', 'Failed')], default='new', max_length=20)),
                ('rca', models.TextField(blank=True)),
                ('proposed_diff', models.TextField(blank=True)),
                ('pr_title', models.CharField(blank=True, max_length=200)),
                ('pr_body', models.TextField(blank=True)),
                ('pr_url', models.URLField(blank=True)),
                ('pr_branch', models.CharField(blank=True, max_length=200)),
                ('last_seen_review_id', models.BigIntegerField(blank=True, null=True)),
                ('last_seen_comment_id', models.BigIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debug_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'debug_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebugMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='debugger.debugrequest')),
            ],
            options={
                'db_table': 'debug_messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DebugLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('query', 'Query')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learnings', to='debugger.debugrequest')),
            ],
            options={
                'db_table': 'debug_learnings',
                'ordering': ['-created_at'],
            },
        ),
    ]
