# Generated by Django 5.2.16 on 2026-07-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugrequest',
            name='learning_draft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='debugrequest',
            name='learning_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='debugrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('analyzing', 'Analyzing'), ('awaiting_input', 'Awaiting input'), ('ready', 'Ready'), ('pr_requested', 'PR requested'), ('pr_open', 'PR open'), ('changes_requested', 'Changes requested'), ('revising', 'Revising'), ('pr_updated', 'PR updated'), ('finalizing', 'Finalizing'), ('learning_review', 'Learning review'), ('closed', 'Closed'), ('failed', 'Failed')], default='new', max_length=20),
        ),
    ]
