# Generated by Django 5.2.16 on 2026-08-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugger', '0004_debuglearning_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugrequest',
            name='proposed_new_files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
