# Generated by Django 5.2.16 on 2026-09-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugger', '0005_debugrequest_proposed_new_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugrequest',
            name='auth_mode',
            field=models.CharField(choices=[('api', 'API (metered)'), ('subscription', 'Subscription (budget)')], default='api', max_length=12),
        ),
    ]
