# Generated by Django 5.2.16 on 2026-09-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debugger', '0006_debugrequest_auth_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debugrequest',
            name='auth_mode',
        ),
    ]
