# Generated by Django 5.2.16 on 2026-10-06 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_b2bcompany_location_url_b2bcompany_photo'),
        ('products', '0007_alter_stockmovement_reference_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'work_session_telegram_report_log',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sales', 'Sales'), ('packing', 'Packing')], max_length=10)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_break', 'On Break'), ('ended', 'Ended')], default='active', max_length=10)),
                ('auto_closed', models.BooleanField(default=False)),
                ('end_edited', models.BooleanField(default=False)),
                ('end_edit_note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work_sessions',
            },
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs', models.PositiveIntegerField()),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.flavor')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='sessions_tracking.session')),
            ],
            options={
                'db_table': 'work_session_packing_items',
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('start', 'Start'), ('break', 'Break'), ('resume', 'Resume'), ('end', 'End')], max_length=10)),
                ('at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, choices=[('lunch_break', 'Lunch Break'), ('evening_break', 'Evening Break')], max_length=20, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sessions_tracking.session')),
            ],
            options={
                'db_table': 'work_session_events',
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_off_weekday', models.PositiveSmallIntegerField(default=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work_session_user_settings',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField()),
                ('purpose', models.CharField(choices=[('new_lead', 'New Lead'), ('retarget', 'Retarget'), ('delivery', 'Delivery'), ('collection', 'Collection'), ('audit', 'Audit'), ('reorder_push', 'Reorder Push')], max_length=20)),
                ('outcome', models.CharField(choices=[('order', 'Order'), ('follow_up', 'Follow Up'), ('rejected', 'Rejected'), ('none', 'None')], default='none', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crm.b2bcompany')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='sessions_tracking.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work_session_visits',
                'ordering': ['visited_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyOffChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_weekday', models.PositiveSmallIntegerField()),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_off_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work_session_weekly_off_changes',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work_session_leaves',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'started_at'], name='worksession_user_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user',), name='one_open_work_session_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='packingitem',
            unique_together={('session', 'flavor')},
        ),
        migrations.AddIndex(
            model_name='sessionevent',
            index=models.Index(fields=['session', 'at'], name='worksession_event_sess_at_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['user', 'visited_at'], name='worksession_visit_user_at_idx'),
        ),
    ]
