# Generated by Django 5.2.16 on 2026-10-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='area',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
