# Generated by Django 5.2.16 on 2026-10-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_tracking', '0002_session_area'),
        # Must run after crm's backfill, which reads this app's Visit table.
        ('crm', '0007_backfill_visit_purpose_outcome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
