# Generated by Django 5.2.16 on 2026-07-17 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_categories', to='core.brand')),
            ],
            options={
                'verbose_name_plural': 'B2B categories',
                'db_table': 'b2b_categories',
            },
        ),
        migrations.CreateModel(
            name='B2BCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('contacted', 'Contacted'), ('negotiation', 'Negotiation'), ('converted', 'Converted'), ('lost', 'Lost')], default='lead', max_length=20)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('amount', 'Amount')], max_length=20)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_terms_days', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_companies', to='core.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='crm.b2bcategory')),
            ],
            options={
                'verbose_name_plural': 'B2B companies',
                'db_table': 'b2b_companies',
            },
        ),
        migrations.CreateModel(
            name='B2BContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.b2bcompany')),
            ],
            options={
                'db_table': 'b2b_contacts',
            },
        ),
        migrations.CreateModel(
            name='B2BActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('note', 'Note'), ('stage_change', 'Stage Change'), ('order', 'Order'), ('payment', 'Payment'), ('return', 'Return')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('old_stage', models.CharField(blank=True, max_length=20)),
                ('new_stage', models.CharField(blank=True, max_length=20)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('is_follow_up_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.b2bcompany')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.b2bcontact')),
            ],
            options={
                'verbose_name_plural': 'B2B activities',
                'db_table': 'b2b_activities',
            },
        ),
    ]
