# Generated by Django 5.2.16 on 2026-07-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bcompany',
            name='location_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='b2bcompany',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='leads/'),
        ),
    ]
