# Generated by Django 5.2.16 on 2026-10-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_b2bcompany_location_url_b2bcompany_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bactivity',
            name='type',
            field=models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('note', 'Note'), ('visit', 'Field Visit'), ('stage_change', 'Stage Change'), ('order', 'Order'), ('payment', 'Payment'), ('return', 'Return')], max_length=20),
        ),
    ]
