# Generated by Django 5.2.16 on 2026-10-06 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_b2bactivity_type'),
        ('orders', '0004_b2border_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bactivity',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='orders.b2border'),
        ),
    ]
