# Generated by Django 5.2.16 on 2026-10-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_backfill_activity_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bactivity',
            name='visit_outcome',
            field=models.CharField(blank=True, choices=[('order', 'Order'), ('follow_up', 'Follow Up'), ('rejected', 'Rejected'), ('none', 'None')], max_length=20),
        ),
        migrations.AddField(
            model_name='b2bactivity',
            name='visit_purpose',
            field=models.CharField(blank=True, choices=[('new_lead', 'New Lead'), ('retarget', 'Retarget'), ('delivery', 'Delivery'), ('collection', 'Collection'), ('audit', 'Audit'), ('reorder_push', 'Reorder Push')], max_length=20),
        ),
    ]
