# Generated by Django 5.2.16 on 2026-10-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_backfill_visit_purpose_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="b2bcompany",
            name="gst_legal_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="b2bcompany",
            name="state_code",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
