# Generated by Django 5.2.16 on 2026-09-13 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('format', models.CharField(choices=[('reel', 'Reel'), ('poster', 'Poster'), ('blog', 'Blog')], max_length=10)),
                ('content_type', models.CharField(blank=True, choices=[('reel_varthaanm', 'Reel — Varthaanm'), ('reel_verdict', 'Reel — Verdict'), ('reel_inside', 'Reel — Inside'), ('poster_learn', 'Poster — Learn With Varthaai'), ('poster_occasion', 'Poster — Occasion'), ('poster_event', 'Poster — Event'), ('blog', 'Blog')], max_length=20)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_alternate_week', models.BooleanField(default=False)),
                ('prep_lead_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('intake_lead_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skill_slug', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'content series',
                'db_table': 'content_series',
            },
        ),
        migrations.CreateModel(
            name='ContentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_plans',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('reel_varthaanm', 'Reel — Varthaanm'), ('reel_verdict', 'Reel — Verdict'), ('reel_inside', 'Reel — Inside'), ('poster_learn', 'Poster — Learn With Varthaai'), ('poster_occasion', 'Poster — Occasion'), ('poster_event', 'Poster — Event'), ('blog', 'Blog')], max_length=20)),
                ('planned_date', models.DateField()),
                ('working_title', models.CharField(max_length=255)),
                ('context_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('needs_input', 'Needs input'), ('ready_for_script', 'Ready for script'), ('scripted', 'Scripted'), ('needs_approval', 'Needs approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('skipped', 'Skipped')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.contentplan')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='content.contentseries')),
            ],
            options={
                'db_table': 'plan_items',
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('input_needed', 'Input needed'), ('plan_review', 'Plan review'), ('script_review', 'Script review'), ('poster_review', 'Poster review')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='content.contentplan')),
                ('plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='content.planitem')),
            ],
            options={
                'db_table': 'action_items',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PosterAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/posters/')),
                ('brief', models.JSONField(blank=True, default=dict)),
                ('inspiration_id', models.PositiveIntegerField(blank=True, null=True)),
                ('generation_metadata', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('changes_requested', 'Changes requested')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='content.planitem')),
            ],
            options={
                'db_table': 'poster_assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_used', models.CharField(max_length=100)),
                ('raw_output', models.TextField(blank=True)),
                ('structured_json', models.JSONField(blank=True, default=dict)),
                ('recap_summary', models.TextField(blank=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('changes_requested', 'Changes requested')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='content.planitem')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scripts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('considered', models.BooleanField(default=False)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trend_flags', to='content.planitem')),
            ],
            options={
                'db_table': 'trend_flags',
                'ordering': ['-flagged_at'],
            },
        ),
    ]
