# Generated by Django 5.2.16 on 2026-09-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentplan_brand'),
        ('core', '0002_brand_brand_kit_brand_brand_kit_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posterasset',
            name='inspiration_id',
        ),
        migrations.AddField(
            model_name='posterasset',
            name='format',
            field=models.CharField(choices=[('1:1', 'Square (1:1) — feed'), ('9:16', 'Story/Reel (9:16)'), ('4:5', 'Portrait (4:5) — feed')], default='1:1', max_length=10),
        ),
        migrations.CreateModel(
            name='PosterInspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_label', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='content/poster_inspirations/')),
                ('description', models.TextField()),
                ('design_language', models.TextField()),
                ('topic_category', models.CharField(db_index=True, max_length=80)),
                ('format', models.CharField(choices=[('1:1', 'Square (1:1) — feed'), ('9:16', 'Story/Reel (9:16)'), ('4:5', 'Portrait (4:5) — feed')], db_index=True, max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('has_logo', models.BooleanField(blank=True, default=None, null=True)),
                ('score', models.PositiveSmallIntegerField(default=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_inspirations', to='core.brand')),
            ],
            options={
                'db_table': 'poster_inspirations',
            },
        ),
        migrations.AddField(
            model_name='posterasset',
            name='inspiration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster_assets', to='content.posterinspiration'),
        ),
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content/brand_assets/')),
                ('tag', models.CharField(choices=[('product', 'Product'), ('lifestyle', 'Lifestyle'), ('team', 'Team'), ('event', 'Event'), ('icon', 'Icon'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_assets', to='core.brand')),
            ],
            options={
                'db_table': 'content_brand_assets',
                'indexes': [models.Index(fields=['brand', 'tag'], name='content_bra_brand_i_0b10fb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='posterinspiration',
            index=models.Index(fields=['topic_category', 'format'], name='poster_insp_topic_c_03abcb_idx'),
        ),
    ]
