# Generated by Django 5.2.16 on 2026-09-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_posterasset_inspiration_id_posterasset_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentplan',
            name='generation_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('needs_review', 'Needs review'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
