# Generated by Django 5.2.16 on 2026-09-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_contentplan_generation_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentseries',
            name='content_type',
            field=models.CharField(blank=True, choices=[('reel_varthaanm', 'Reel — Varthaai Varthaanm'), ('reel_verdict', 'Reel — Varthaai Verdict'), ('reel_inside', 'Reel — Varthaai Inside'), ('poster_learn', 'Poster — Learn With Varthaai'), ('poster_occasion', 'Poster — Occasion'), ('poster_event', 'Poster — Event'), ('blog', 'Blog')], max_length=20),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='content_type',
            field=models.CharField(choices=[('reel_varthaanm', 'Reel — Varthaai Varthaanm'), ('reel_verdict', 'Reel — Varthaai Verdict'), ('reel_inside', 'Reel — Varthaai Inside'), ('poster_learn', 'Poster — Learn With Varthaai'), ('poster_occasion', 'Poster — Occasion'), ('poster_event', 'Poster — Event'), ('blog', 'Blog')], max_length=20),
        ),
    ]
