# Generated by Django 5.2.16 on 2026-09-14 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_contentseries_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planitem',
            name='proposed_changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='posterasset',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posterasset',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posterasset',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='kind',
            field=models.CharField(choices=[('input_needed', 'Input needed'), ('plan_review', 'Plan review'), ('item_change_proposed', 'Plan item change proposed'), ('script_review', 'Script review'), ('poster_review', 'Poster review')], max_length=20),
        ),
    ]
