# Generated by Django 5.2.16 on 2026-09-14 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_planitem_proposed_changes_posterasset_review_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerdictIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('market', models.CharField(blank=True, default='India', max_length=100)),
                ('price_point', models.CharField(blank=True, max_length=100)),
                ('product_photo', models.ImageField(blank=True, upload_to='content/verdict/')),
                ('ingredients_label_photo', models.ImageField(blank=True, upload_to='content/verdict/')),
                ('ingredients_text', models.TextField(blank=True)),
                ('nutrition_label_photo', models.ImageField(blank=True, upload_to='content/verdict/')),
                ('nutrition_text', models.TextField(blank=True)),
                ('design_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('design_notes', models.TextField(blank=True)),
                ('pricing_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pricing_notes', models.TextField(blank=True)),
                ('taste_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('taste_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verdict_intake', to='content.planitem')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verdict_intakes',
            },
        ),
    ]
