# Generated by Django 5.2.16 on 2026-09-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_verdictintake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandasset',
            name='tag',
            field=models.CharField(choices=[('logo', 'Logo'), ('product', 'Product'), ('lifestyle', 'Lifestyle'), ('team', 'Team'), ('event', 'Event'), ('icon', 'Icon'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
