# Generated by Django 5.2.16 on 2026-10-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_b2borderitem_returned_quantity_b2breturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2border',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
