# Generated by Django 5.2.16 on 2026-10-10 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("orders", "0004_b2border_delivered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="b2border",
            name="customer_po_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="b2border",
            name="customer_po_no",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="b2border",
            name="gst_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="b2border",
            name="place_of_supply_state",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="b2border",
            name="price_mode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="b2border",
            name="ship_to_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="b2border",
            name="ship_to_gstin",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="b2border",
            name="ship_to_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="b2border",
            name="ship_to_pincode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="b2border",
            name="ship_to_same_as_bill_to",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="b2border",
            name="ship_to_state_code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="b2breturn",
            name="credit_note",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="b2b_return",
                to="billing.creditnote",
            ),
        ),
        migrations.AddField(
            model_name="b2breturn",
            name="needs_credit_note",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="gst_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="price_mode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_state_code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="b2bpayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("upi", "UPI"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cheque", "Cheque"),
                    ("credit_adjustment", "Credit Adjustment"),
                    ("online", "Online"),
                ],
                max_length=20,
            ),
        ),
    ]
