# Generated by Django 5.2.16 on 2026-07-17 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('fssai_number', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_per_kg', models.FloatField(default=1490)),
                ('sale_price_per_kg', models.FloatField(default=990)),
                ('reorder_level_grams', models.IntegerField(default=5000)),
                ('is_active', models.BooleanField(default=True)),
                ('ingredients', models.TextField(blank=True)),
                ('nutrition_fact', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flavors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavors', to='core.brand')),
            ],
            options={
                'db_table': 'flavors',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_batch', models.BooleanField(default=False)),
                ('quantity_grams', models.IntegerField(default=0)),
                ('reserved_quantity_grams', models.IntegerField(default=0)),
                ('cost_price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('supplier_contact', models.CharField(blank=True, max_length=255)),
                ('last_restocked_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('storage_location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='products.flavor')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='products.vendor')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired')], max_length=20)),
                ('current_quantity_grams', models.IntegerField()),
                ('reorder_level_grams', models.IntegerField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.flavor')),
            ],
            options={
                'db_table': 'stock_alerts',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('adjustment', 'Adjustment'), ('reserved', 'Reserved'), ('released', 'Released')], max_length=20)),
                ('quantity_grams', models.IntegerField()),
                ('previous_quantity_grams', models.IntegerField()),
                ('new_quantity_grams', models.IntegerField()),
                ('reference_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('wastage', 'Wastage'), ('adjustment', 'Adjustment'), ('order_reserve', 'Order Reserve'), ('order_release', 'Order Release'), ('b2b_sale', 'B2B Sale'), ('b2b_reversal', 'B2B Reversal')], max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=50)),
                ('cost_price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.flavor')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='products.stock')),
            ],
            options={
                'db_table': 'stock_movements',
            },
        ),
        migrations.CreateModel(
            name='FlavorPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_grams', models.IntegerField()),
                ('label', models.CharField(max_length=50)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='products.flavor')),
            ],
            options={
                'db_table': 'flavor_packs',
                'unique_together': {('flavor', 'weight_grams')},
            },
        ),
    ]
