# Generated by Django 5.2.16 on 2026-08-09 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_finalize_flavor_global_pack_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='supplier_name',
        ),
    ]
