# Generated by Django 5.2.16 on 2026-08-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_stock_supplier_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('sample', 'Sample'), ('wastage', 'Wastage'), ('adjustment', 'Adjustment'), ('order_reserve', 'Order Reserve'), ('order_release', 'Order Release'), ('b2b_sale', 'B2B Sale'), ('b2b_reversal', 'B2B Reversal')], max_length=20),
        ),
    ]
