# Generated by Django 5.2.16 on 2026-10-10 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("products", "0007_alter_stockmovement_reference_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="flavor",
            name="hsn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flavors",
                to="billing.hsncode",
            ),
        ),
    ]
